export default {
  loginwelcome: 'Welcome to Star Loyalty!',
  logintext: 'Sign in to earn benefits',
  otptext: 'OTP Verification',
  otpheading: 'Enter the OTP sent to your mobile',
  signIn: 'Sign In',
  signUp: 'Sign Up',
  verify: 'Verify',
  next: 'Next',
  gotologin: 'Go To Login',
  gotoHome: 'Go To Home',
  success: 'Success',
  redeemMore: "REDEEM MORE POINTS",
  transferMore: "TRANSFER MORE POINTS",
  purchase_Successful: "Purchase Successful",
  regisrationReward: "A voucher code has been sent to your registered email.",
  registrationMessage:
    'Registered successfully. Please sign in to start using the app.',
  did_not_receive: 'Didn’t receive it?',
  resend: 'Resend',
  choose_your_interests: 'Choose your interests',
  interests: 'Interests',
  Choose_your_areas:
    'Choose your areas of interest to make the experience even better',
  your_information: 'Your information',
  let_us_know: 'Let us know a little bit about you',
  redeemed: 'Redeemed',
  redeemText: "Redeem",
  redeemNow: "REDEEM NOW",
  transfer: "Transfer",
  earned: 'Earned',
  savings: 'Savings',
  expired: 'Expired',
  points_expire: '1,200 points expire in 7 days.',
  timeline: 'Timeline',
  available_offers: 'Available Offers',
  see_all: 'See all',
  recommended_for_you: 'Recommended for you',
  explore: 'Explore',
  games_for_you: 'Games for you',
  swipeOffer: 'SWIPE TO GET OFFER',
  swipeBuy: 'SWIPE TO BUY',
  share: 'Share',
  tcn: 'Terms & Conditions',
  redeem: 'How to redeem',
  reward: 'Rewards',
  vouchers: "Vouchers",
  toReward: 'Top Rewards',
  shopping: 'Shopping',
  travel: 'Travel',
  clear: 'Clear',
  recentSearch: 'Recent Searches',
  search_Results: 'Search Results',
  popular_Searches: 'Popular Searches',
  historyTitle: 'History',
  filter: 'Filter',
  apply: 'APPLY',
  cancel: 'CANCEL',
  manageProfile: 'Manage Profile',
  editProfile: 'Edit Profile',
  associated_Members: 'Associated Members',
  no_members_to_show: 'No members to show',
  loyalty_Points: 'Loyalty Points',
  membership_ID: ' Membership ID',
  transactions: "Transactions",
  name: "Name",
  calcelVouchers: "CANCEL VOUCHER",
  yes: "Yes",
  no: "No",
  ok: "Ok",
  tap_TO_SPIN: "TAP TO SPIN",
  justspnning: "Just tap on the button to spin the wheel and claim your prize!",
  spinWheel: "Spin the Wheel",
  ya_Congratulations: "Yay! Congratulations!",
  cashback: "Cashback",
  transfer_Points: "Transfer Points",
  transfer_now: "Transfer Now",
  transfer_PointsDis: "Transfer points as gift to your friends & family.",
  notification: "Notification",
  notifications: "Notifications",
  select: "Select",
  allNotificaion: "All notifications",
  markread: "Mark read",
  delete: "Delete",
  setting: "Settings",
  changeLanguage: "Change Language",
  quiz: "Take a Quiz",
  survey: "Take a Survey",
  submit: "Submit",
  takeSurveyHeading: "Take the survey & get 200 Loyalty points",
  swipExchange: "SWIPE TO EXCHANGE",
  exchangeNow: "EXCHANGE NOW",
  referT: 'Refer a friend and \n earn $10',
  referD: "Invite a friend to register with Mobilytix \n Rewards and you both will earn $10."
};
